substitutions:
  name: "igrow-ae0490"
packages:
  esphome.project-template: github://pbezant/LILYGO-T-Higrow-Esphome/LILYGO-T-Higrow-ESP32.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: +A++IjW8R163LmDQAr41u1HFjLnDB1ks9irIaNHRcqA=

wifi:
  ssid: Drop It Like It's Hotspot
  password: eaglemonth065
  domain: .lan
